export default [
    {
        label:'首页',
        controller_name:'index',
        icon:'setting',
        children:[
            {
                method_name:'index',
                component:resolve=>require(['@/pages/index/index'],resolve),
                label:'个人中心',
                meta:{
                    privilege:[1],
                    base_url:'/index/user',
                },
            },
            {
                method_name:'abc',
                component:resolve=>require(['@/pages/index/index'],resolve),
                label:'abcpahe',
                meta:{
                    privilege:[1],
                    base_url:'/index/user',
                },
            },
        ],
    },
    {
        label:'客户中心',
        controller_name:'crm',
        icon:'share',
        children:[
            {
                method_name:'index',
                component:resolve=>require(['@/pages/crm/index'],resolve),
                label:'客户首页',
                meta:{
                    privilege:[1],
                },
            },
            {
                method_name:'crm',
                component:resolve=>require(['@/pages/crm/crm'],resolve),
                label:'客户',
                meta:{
                    privilege:[1],
                },
            }

        ],
    },
];