import {
    getStore,
    getSaler,
    getCreateFields,
    createBook,
    getBookList,
} from "@/server/book.js"

export default{
    field_list:{
        customername:{
            label:'客户名',
            editorComponent:{
                name:"field_string",
                config:{
                    placeholder:'请输入客户名',
                },
                default:'',
            },
        },
        totalprice:{
            label:'金额',
            editorComponent:{
                name:"field_number",
                default:0,
            },
        },
        address:{
            label:"收货地址",
            editorComponent:{
                name:"field_text",
                default:"",
            },
        },
        store:{
            label:"店铺",
            editorComponent:{
                name:"field_async_enum_select",
                config:{
                    httpRequest:getStore,
                    labelfield:"storename",
                    valuefield:"_id",
                },
                default:"",
            },
        },
        saler:{
            label:"销售",
            editorComponent:{
                name:"field_relates_enum_select",
                config:{
                    relates:[
                        {
                            invalidValue:"",
                            relateField:"store",
                        }
                    ],
                    httpRequest:getSaler,
                },
                default:"",
            },
        },
    },
    createConfig:{
        getInfoRequest:getCreateFields,
        doCreateRequest:createBook,
    },
    listConfig:{
        listRequest:getBookList,
    },
    filters:[
        {
            label:"客户名",
            field:"customername",
            editorComponent:{
                name:"field_string",
                config:{
                    placeholder:"请输入客户名"
                },
                default:"",
            }
        },
        {
            label:"金额",
            field:"totalprice",
            editorComponent:{
                name:"field_number",
                default:500,
            }
        },
    ],
    operators:[
        {
            label:"再来一单",
            type:"success",
            function(data){
                this.$message({
                    message:`${data.customername}再来一单`,
                    type:"success",
                    duration:2000
                })
            }
        }

    ],
}