export default{
    field_list:{
        name:{
            label:'用户名',
            editor:'field_string',
            placeholder:'请输入用户名',
            default:'',
        },
        password:{
            label:'密码',
            editor:'field_pwd',
            placeholder:'请输入密码',
            default:'',
        },
        gender:{
            label:'性别',
            editor:'field_sex',
            default:0,
        },
        typ:{
            label:'类型',
            editor:'field_enum_select',
            candidate:[
                {value:0,label:'路人甲'},
                {value:1,label:'店小二'},
                {value:2,label:'收银员'},
                {value:99,label:'店掌柜'},
                {value:999,label:'管理员'},
            ],
            default:0,
            valuefield:'value',
            labelfield:'label',
        },
        privilege:{
            label:'权限',
            editor:"field_relates_tag",
            uri:'/user/getPrivilege',
            labelfield:'name',
            valuefield:'id',
            relates:{
                usertyp:{
                    inValidValue:0,
                    relatefield:'typ'
                }
            },
            default(){
                return [];
            }
        },
    },
    create_link:'/user/create_link',
    docreate_link:'/user/docreate',
}